baseURL = "http://example.com/"
languageCode = "en-us"
title = "My Hugo Site"
theme = "risotto"

enableEmoji = true

[params]
author = "Your Name"
description = "My awesome Hugo site"


[build]
  duplicateResourceFiles = false
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = false
[[build.cacheBusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = '(css|styles|scss|sass)'